add datePicker, Card, Modal components, and refactor stylelint - add keyframes-name-pattern null for kebab case (#50)
* refactor import paths

* add datePicker, Card, Modal components, and refactor stylelint - add keyframes-name-pattern null for kebab case

* add datePicker, Card, Modal components, and refactor stylelint - add keyframes-name-pattern null for kebab case

---------

Co-authored-by: Daniil <daniilminin1990@yandex.ru>

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,12 +1,15 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-pnpm run format
-
 echo '🏗️👷 Styling, testing and building your project before committing'
 
 if ! pnpm run check-format; then
     echo '❌ Prettier Check Failed. Run pnpm run format,  Problem pnpm run check-format , add changes and try commit again. ❌'
+    exit 1
+fi
+
+if ! pnpm run format; then
+    echo '❌ Prettier Format Failed. Problem pnpm run format , add changes and try commit again. ❌'
     exit 1
 fi
 
